name: Daily News Fetch and Send to WeChat

on:
  schedule:
    # 设置每天的某个时间触发工作流（例如：每天 8:00 AM UTC）
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  fetch-and-send-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install newspaper3k openai requests

      - name: Fetch News and Interpret with AI
        run: |
          python <<EOF
          import openai
          import requests
          from newspaper import Article
          # 获取新闻文章
          def fetch_news():
          url = 'rsshub://twitter/media/435hz'  # 请替换为你选择的新闻源 URL
          article = Article(url)
          article.download()
          article.parse()
          return article.title + '\\n' + article.text

          # 使用自定义 OpenAI API 解读新闻
          def interpret_news(news):
              openai.api_base = 'https://your-custom-openai-endpoint.com/v1'  # 自定义 OpenAI 端点
              openai.api_key = '${{ secrets.OPENAI_API_KEY }}'  # 从 GitHub Secrets 中获取 OpenAI API 密钥
              response = openai.Completion.create(
                  model="gpt-4o-mini",  # 使用 gpt-4o-mini 模型
                  prompt=f"Please summarize the following news article:\n\n{news}",
                  max_tokens=200
              )
              return response.choices[0].text.strip()
          
          # 主流程：抓取新闻、解读、并通过 Server 酱发送
          news = fetch_news()
          summary = interpret_news(news)
          sckey = '${{ secrets.SERVERPUSHKEY }}'  # 从 GitHub Secrets 中获取 Server 酱推送密钥
          message = f"新闻摘要：\n{summary}"
          requests.get(f"https://sc.ftqq.com/{sckey}.send?text=每日新闻摘要&desp={message}")
          EOF
          
                - name: Finish
                  run: echo "News fetched, interpreted, and sent to WeChat."
