name: Daily News Fetch and Send to WeChat

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  fetch-and-send-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install newspaper3k openai requests lxml[html_clean]  # 添加缺失的依赖

      - name: Fetch News and Interpret with AI
        run: |
          python << 'EOF'
          import openai
          import requests
          from newspaper import Article
      
          def fetch_news():
              # 注意：BBC首页需要特殊处理，这里可能需要调整
              url = 'https://www.bbc.com/news'
              article = Article(url)
              article.download()
              article.parse()
              return article.title + '\n' + article.text
      
          def interpret_news(news):
              openai.api_base = 'https://api.chatanywhere.com.cn/v1'
              openai.api_key = '${{ secrets.OPENAI_API_KEY }}'
              response = openai.Completion.create(
                  model="gpt-4o-mini",
                  prompt=f"Please summarize the following news article:\n\n{news}",
                  max_tokens=200
              )
              return response.choices[0].text.strip()
      
          if __name__ == "__main__":
              news = fetch_news()
              summary = interpret_news(news)
              sckey = '${{ secrets.SERVERPUSHKEY }}'
              message = f"新闻摘要：\n{summary}"
              requests.get(f"https://sc.ftqq.com/{sckey}.send?text=每日新闻摘要&desp={message}")
          EOF
          
      - name: Finish
        run: echo "News fetched, interpreted, and sent to WeChat."
