name: Daily News Fetch and Send to WeChat

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  fetch-and-send-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install newspaper3k "openai>=1.0" requests lxml[html_clean]

      - name: Fetch News and Interpret with AI
        run: |
          python << 'EOF'
          from openai import OpenAI
          import requests
          from newspaper import Article
          import os
      
          def fetch_news():
              url = 'https://www.bbc.com/news/world-60525350'  # 改用具体文章地址
              article = Article(url)
              article.download()
              article.parse()
              return article.title + '\n' + article.text
      
          def interpret_news(news):
              client = OpenAI(
                  base_url = "https://api.chatanywhere.com.cn/v1",
                  api_key = os.getenv('OPENAI_API_KEY')
              )
              response = client.chat.completions.create(
                  model="gpt-4o-mini",  # 确认可用模型名称
                  messages=[{
                      "role": "user",
                      "content": f"请用中文总结这篇新闻，控制在200字内：\n\n{news}"
                  }]
              )
              return response.choices[0].message.content
      
          if __name__ == "__main__":
              news = fetch_news()
              summary = interpret_news(news)
              sckey = os.getenv('SERVERPUSHKEY')
              message = f"新闻摘要：\n{summary}"
              requests.get(f"https://sc.ftqq.com/{sckey}.send?text=每日新闻摘要&desp={message}")
          EOF
          
      - name: Finish
        run: echo "News fetched, interpreted, and sent to WeChat."
