name: Daily News Fetch and Send to WeChat

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  fetch-and-send-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install newspaper3k "openai>=1.0" requests lxml[html_clean]

      - name: Fetch News and Interpret with AI
        env:  # 添加环境变量传递
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
        run: |
          python << 'EOF'
          from openai import OpenAI
          import requests
          from newspaper import Article
          import os
      
          def fetch_news():
              url = 'https://www.bbc.com/news/world-60525350'
              article = Article(url)
              article.download()
              article.parse()
              return f"{article.title}\n\n{article.text}"
      
          def interpret_news(news):
              print("API Key exists:", bool(os.getenv("OPENAI_API_KEY")))
              client = OpenAI(
                  base_url = "https://api.chatanywhere.org/v1",
                  api_key = os.environ["OPENAI_API_KEY"]  # 使用更明确的获取方式
              )
              
              response = client.chat.completions.create(
                  model="gpt-4o-mini",
                  messages=[{
                      "role": "user",
                      "content": f"请用中文总结这篇新闻，控制在200字内：\n\n{news}"
                  }]
              )
              return response.choices[0].message.content
      
          if __name__ == "__main__":
              try:
                  news = fetch_news()
                  summary = interpret_news(news)
                  sckey = os.environ["SERVERPUSHKEY"]
                  
                  # URL编码处理
                  from urllib.parse import quote
                  encoded_msg = quote(f"新闻摘要：\n{summary}")
                  
                  requests.get(
                      f"https://sctapi.ftqq.com/{sckey}.send",
                      params={
                          "text": "每日新闻摘要",
                          "desp": encoded_msg
                      }
                  )
              except Exception as e:
                  print(f"程序执行失败: {str(e)}")
                  raise
          EOF
          
      - name: Finish
        run: echo "News fetched, interpreted, and sent to WeChat."
